name: Deploy - Container

on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        required: true
      s3_bucket_region:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true    
      S3_BUCKET:
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          cd ${{ env.PACKAGE_NAME }}
          echo "::set-output name=dir::$(yarn cache dir)"
      
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        working-directory: ${{ inputs.working_directory }}
        shell: bash
        run: |
          yarn install
         
      - name: Build
        working-directory: ${{ inputs.working_directory }}
        shell: bash
        run: |
          yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Deploy
        working-directory: ${{ inputs.working_directory }}
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ inputs.s3_bucket_region }}
          dist-id: ${{ secrets.CF_DIST_ID }}
          invalidation: /*
          delete-removed: true
          no-cache: false